'\" t
.TH samtools-stats 1 "14 August 2018" "samtools-1.9" "Bioinformatics tools"
.SH NAME
samtools stats \- produces comprehensive statistics from alignment file
.\"
.\" Copyright (C) 2008-2011, 2013-2018 Genome Research Ltd.
.\" Portions copyright (C) 2010, 2011 Broad Institute.
.\"
.\" Author: Heng Li <lh3@sanger.ac.uk>
.\" Author: Joshua C. Randall <jcrandall@alum.mit.edu>
.\"
.\" Permission is hereby granted, free of charge, to any person obtaining a
.\" copy of this software and associated documentation files (the "Software"),
.\" to deal in the Software without restriction, including without limitation
.\" the rights to use, copy, modify, merge, publish, distribute, sublicense,
.\" and/or sell copies of the Software, and to permit persons to whom the
.\" Software is furnished to do so, subject to the following conditions:
.\"
.\" The above copyright notice and this permission notice shall be included in
.\" all copies or substantial portions of the Software.
.\"
.\" THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
.\" IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
.\" FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL
.\" THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
.\" LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
.\" FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
.\" DEALINGS IN THE SOFTWARE.
.
.\" For code blocks and examples (cf groff's Ultrix-specific man macros)
.de EX

.  in +\\$1
.  nf
.  ft CR
..
.de EE
.  ft
.  fi
.  in

..
.
.SH SYNOPSIS
.PP
samtools stats
.RI [ options ]
.IR in.sam | in.bam | in.cram
.RI [ region ...]

.SH DESCRIPTION
.PP
samtools stats collects statistics from BAM files and outputs in a text format.
The output can be visualized graphically using plot-bamstats.

A summary of output sections is listed below, followed by more
detailed descriptions.

.TS
lb l .
CHK     checksum
SN      summary numbers
FFQ     First fragment qualities
LFQ     Last fragment qualities
GCF     GC content of first fragments
GCL     GC content of last fragments
GCC     ACGT content per cycle
FBC     ACGT content per cycle for first fragments only
LBC     ACGT content per cycle for last fragments only
BCC1    ACGT content per cycle for BC barcode
CRC1    ACGT content per cycle for CR barcode
OXC1    ACGT content per cycle for OX barcode
RXC1    ACGT content per cycle for RX barcode
QTQ1    Quality distribution for BC barcode
CYQ1    Quality distribution for CR barcode
BZQ1    Quality distribution for OX barcode
QXQ1    Quality distribution for RX barcode
IS      Insert sizes
RL      Read lengths
FRL     Read lengths for first fragments only
LRL     Read lengths for last fragments only
ID      Indel size distribution
IC      indels per cycle
COV     Coverage (depth) distribution
GCD     GC-depth
.TE

Not all sections will be reported as some depend on the data being
coordinate sorted while others are only present when specific barcode
tags are in use.

The CHK row contains distinct CRC32 checksums of read names, sequences
and quality values.  The checksums are computed per alignment record
and summed, meaning the checksum does not change if the input file has
the sort-order changed.

The SN section contains a series of counts, in a similar style to
.BR "samtools stats" ,
but more comprehensive.

The FFQ and LFQ sections report the quality distribution per
first/last fragment and per cycle number.  They have one row per cycle
(reported as the first column after the FFQ/LFQ key) with remaining
columns being the observed integer counts per quality value, starting
at quality 0 in the left-most row and ending at the largest observed
quality.  Thus each row forms its own quality distribution and any
cycle specific quality artefacts can be observed.

GCF and GCL report the total GC content of each fragment, separated
into first and last fragments.  The columns show the GC percentile
(between 0 and 100) and an integer count of fragments at that
percentile.

GCC, FBC and LBC report the nucleotide content per cycle either combined
(GCC) or split into first (FBC) and last (LBC) fragments.  The columns
are cycle number (integer), and percentage counts for A, C, G, T, N
and other (typically containing ambiguity codes) normalised against
the total counts of A, C, G and T only (excluding N and other).

BCC1, CRC1, OXC1 and RXC1 are the barcode equivalent of GCC, showing
nucleotide content for the barcode tags BC, CR, OX and RX respectively.
Their quality values distributions are in the QTQ1, CYQ1, BZQ1 and
QXQ1 sections, corresponding to the BC/QT, CR/CY, OX/BZ and RX/QX SAM
format sequence/quality tags.  These quality value distributions
follow the same format used in the FFQ and LFQ sections.
Note if a separator is present in the SAM tag (usually a hyphen) to
indicate dual indexing, then sections ending in "2" will also be
reported to show the second tag statistics (e.g. both BCC1 and
BCC2 are present).

IS reports insert size distributions with one row per size, reported
in the first column, with subsequent columns for the frequency of
total pairs, inward oriented pairs, outward orient pairs and other
orientation pairs.  The \fB-i\fR option specifies the maximum insert
size reported.

RL reports the distribution for all read lengths, with one row per
observed length (up to the maximum specified by the \fB-l\fR option).
Columns are read length and frequency.  FRL and LRL contains the same
information separated into first and last fragments.

ID reports the distribution of indel sizes, with one row per observed
size. The columns are size, frequency of insertions at that size and
frequency of deletions at that size.

IC reports the frequency of indels occurring per cycle, broken down by
both insertion / deletion and by first / last read.  Note for
multi-base indels this only counts the first base location.  Columns
are cycle, number of insertions in first fragments, number of
insertions in last fragments, number of deletions in first fragments,
and number of deletions in last fragments.

COV reports a distribution of the alignment depth per covered
reference site.  For example an average depth of 50 would ideally
result in a normal distribution centred on 50, but the presence of
repeats or copy-number variation may reveal multiple peaks at
approximate multiples of 50.  The first column is an inclusive
coverage range in the form of \fB[\fImin\fB-\fImax\fB]\fR.  The next
columns are a repeat of the \fImax\fRimum portion of the depth range
(now as a single integer) and the frequency that depth range was
observed.  The minimum, maximum and range step size are controlled by
the \fB-c\fR option.  Depths above and below the minimum and maximum
are reported with ranges \fB[<\fImin\fB]\fR and \fB[\fImax\fB<]\fR.

GCD reports the GC content of the reference data aligned against per
alignment record, with one row per observed GC percentage reported as
the first column and sorted on this column.  The second column is a
total sequence percentile, as a running total (ending at 100%).  The
first and second columns may be used to produce a simple distribution
of GC content.  Subsequent columns list the coverage depth at 10th,
25th, 50th, 75th and 90th GC percentiles for this specific GC
percentage, revealing any GC bias in mapping.  These columns are
averaged depths, so are floating point with no maximum value.

.SH OPTIONS
.TP 8
.BI "-c, --coverage " MIN , MAX , STEP
Set coverage distribution to the specified range (MIN, MAX, STEP all given as integers)
[1,1000,1]
.TP
.B -d, --remove-dups
Exclude from statistics reads marked as duplicates
.TP
.BI "-f, --required-flag "  STR "|" INT
Required flag, 0 for unset. See also `samtools flags`
[0]
.TP
.BI "-F, --filtering-flag " STR "|" INT
Filtering flag, 0 for unset. See also `samtools flags`
[0]
.TP
.BI "--GC-depth " FLOAT
the size of GC-depth bins (decreasing bin size increases memory requirement)
[2e4]
.TP
.B -h, --help
This help message
.TP
.BI "-i, --insert-size " INT
Maximum insert size
[8000]
.TP
.BI "-I, --id " STR
Include only listed read group or sample name
[]
.TP
.BI "-l, --read-length " INT
Include in the statistics only reads with the given read length
[-1]
.TP
.BI "-m, --most-inserts " FLOAT
Report only the main part of inserts
[0.99]
.TP
.BI "-P, --split-prefix " STR
A path or string prefix to prepend to filenames output when creating
categorised statistics files with
.BR -S / --split .
[input filename]
.TP
.BI "-q, --trim-quality " INT
The BWA trimming parameter
[0]
.TP
.BI "-r, --ref-seq " FILE
Reference sequence (required for GC-depth and mismatches-per-cycle calculation).
[]
.TP
.BI "-S, --split " TAG
In addition to the complete statistics, also output categorised statistics
based on the tagged field
.I TAG
(e.g., use
.B --split RG
to split into read groups).

Categorised statistics are written to files named
.RI < prefix >_< value >.bamstat,
where
.I prefix
is as given by
.B --split-prefix
(or the input filename by default) and
.I value
has been encountered as the specified tagged field's value in one or more
alignment records.
.TP
.BI "-t, --target-regions " FILE
Do stats in these regions only. Tab-delimited file chr,from,to, 1-based, inclusive.
[]
.TP
.B "-x, --sparse"
Suppress outputting IS rows where there are no insertions.
.TP
.B "-p, --remove-overlaps"
Remove overlaps of paired-end reads from coverage and base count computations.
.TP
.BI "-g, --cov-threshold " INT
Only bases with coverage above this value will be included in the target percentage computation [0]
.RE

.SH AUTHOR
.PP
Written by Petr Danacek with major modifications by Nicholas Clarke,
Martin Pollard, Nicholas Clarke, Josh Randall and Valeriu Ohan, all
from the Sanger Institute.

.SH SEE ALSO
.IR samtools (1),
.IR samtools-flagstat (1),
.IR samtools-idxstats (1)
.PP
Samtools website: <http://www.htslib.org/>
