name: Windows/MinGW-W64 CI
on: [push, pull_request]

jobs:
  build:
    runs-on: windows-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        ref: ${{ github.event.pull_request.head.sha }}
    - name: Set up MSYS2 MinGW-W64
      uses: msys2/setup-msys2@v2
      with:
        msystem: mingw64
        update: false
        install: >-
          mingw-w64-x86_64-toolchain
          mingw-w64-x86_64-autotools
          mingw-w64-x86_64-curl
          mingw-w64-x86_64-libdeflate
          mingw-w64-x86_64-tools-git
          mingw-w64-x86_64-zlib
          mingw-w64-x86_64-bzip2
          mingw-w64-x86_64-xz
          mingw-w64-x86_64-ncurses
    - name: Clone htslib
      shell: msys2 {0}
      run: |
        export PATH="$PATH:/mingw64/bin:/c/Program Files/Git/bin"
        export MSYSTEM=MINGW64
        htslib_pr=`git log -2 --format='%s' | sed -n 's/.*htslib#\([0-9]*\).*/\1/p'`
        .ci_helpers/clone ${GITHUB_REPOSITORY_OWNER} htslib htslib ${GITHUB_HEAD_REF:-$GITHUB_REF_NAME} $htslib_pr
        pushd .
        cd htslib
        autoreconf -i
        popd
    - name: Compile samtools
      shell: msys2 {0}
      run: |
        export PATH="$PATH:/mingw64/bin:/c/Program Files/Git/bin"
        export MSYSTEM=MINGW64
        autoheader
        autoconf -Wno-syntax
        ./configure --enable-werror
        make -j4
    - name: Check samtools
      shell: msys2 {0}
      run: |
        export PATH="$PATH:/mingw64/bin:/c/Program Files/Git/bin"
        export MSYSTEM=MINGW64
        make check

